name: Build Tawakkal Allah App

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Install required SDK packages
        run: sdkmanager "platforms;android-33" "build-tools;33.0.0"

      - name: Give permission to gradlew
        run: chmod +x gradlew

      - name: Download dependencies
        run: ./gradlew dependencies

      - name: Build Debug APK
        run: ./gradlew assembleDebug

     - uses: actions/upload-artifact@v4
  with:
    name: app-apk
    path: app/build/outputs/apk/release/app-release.apk
