name: Android CI (Debug APK)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ✅ Gradle wrapper ko executable banana (yeh step missing hota hai aksar)
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # ✅ Java 17 (AGP 8.x ke liye)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    # Optional: Android SDK cache thoda speed ke liye
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    # 🧹 Clean + Build (Debug)
    - name: Build Debug APK
      run: ./gradlew clean assembleDebug --stacktrace --warning-mode all

    # 📦 Artifact upload (APK ko download karne ke liye)
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: |
          **/build/outputs/apk/debug/*.apk
          **/outputs/apk/debug/*.apk
